services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres_staging
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:5432"
        env_file:
            - .env.staging
        volumes:
            - postgres_db_vol:/var/lib/postgresql/data
        networks:
            - staging-net

    arthurlobo-api:
        container_name: arthurlobo-api-staging
        build:
            context: .
            dockerfile: apps/arthurlobo-api/Dockerfile
        restart: always
        ports:
            - "${API_PORT}:3001"
        env_file:
            - .env.staging
        depends_on:
            - postgres
        networks:
            - staging-net

    arthurlobo-web:
        container_name: arthurlobo-web-staging
        build:
            context: .
            dockerfile: apps/arthurlobo-web/Dockerfile
        restart: always
        ports:
            - "${WEB_PORT}:3000"
        env_file:
            - .env.staging
        networks:
            - staging-net

volumes:
    postgres_db_vol: {}

networks:
    staging-net:
        driver: bridge
